services:
  postgres:
    image: postgres:17
    container_name: postgres-sample
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./samples:/samples
    restart: unless-stopped

volumes:
  postgres-data: 